### PR TITLE
Add rustconf

### PR DESCRIPTION
**Pull request by dns2utf8**
I am not involved with the conference so this is my best guess

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
Thank you for your PR!

**Comment by dns2utf8** [comment]
You are welcome! For some reason, at least for me, there are still no events visible on https://timetill.rs/

**Comment by XAMPPRocky** [comment]
@dns2utf8 Oh yeah, that was odd. Some reason it's started skipping the `if:` in the CI, I've fixed it now.

**Comment by dns2utf8** [comment]
Thanks!

**Pull request merged**
